---
- name: Elasticsearch - Restart service
  service: 
        name: elasticsearch
        state: restarted
        enabled: yes

- name: Graylog - Restart service
  service:
          name: graylog-server
          state: restarted
          enabled: yes

- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true
          
