---
# tasks file for configure_network_OpenVPN_server

- name: Setup networking and ufw /etc/sysctl.conf
  sysctl:
         name: net.ipv4.ip_forward
         value: 1
         sysctl_set: yes
         state: present
         reload: yes

- name: Setup networking and ufw /etc/default/ufw , ACCEPTING FORWARDING POLICY
  replace:
          path: /etc/default/ufw
          regexp: DEFAULT_FORWARD_POLICY="DROP"
          replace: DEFAULT_FORWARD_POLICY="ACCEPT"

- name: Adding POSTROUTING rules
  lineinfile:
             path: /etc/ufw/before.rules
             state: present
             insertbefore: BOF
             line: |
                   *nat
                   :POSTROUTING ACCEPT [0:0]
                   -A POSTROUTING -s 10.8.0.0/8 -o {{ ethernetInterface }} -j MASQUERADE
                   COMMIT

- name: Allow logging in syslog
  ufw:
      logging: on

- name: UFW allow SSH
  ufw:
      rule: allow
      name: OpenSSH

- name: UFW allow OpenVPN
  ufw:
      rule: allow
      port: 1194     
  notify: Restart ufw service           

- name: UFW enable
  ufw:
      state: enabled

- name: Start and enable openvpn@server.service at boot
  service:
          name: openvpn@server
          state: restarted
          enabled: yes

